language: node_js
sudo: true
node_js: 12
script:
  - npm run lint
  - npm run codecov
env:
  global:
    - BX_APP=language-translator-demo
    - BX_API=https://api.ng.bluemix.net
    - BX_ORGANIZATION=WatsonPlatformServices
    - BX_SPACE=demos
before_deploy: npm install -g bx-blue-green
deploy:
  - provider: script
    script: bx-blue-green-travis
    on:
      branch: master
      repo: watson-developer-cloud/language-translator-nodejs
    skip_cleanup: true
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
